#!/bin/sh
url=$(curl -s wanghui.cfapps.io/wallpaper.do)
folder=$HOME/Pictures/Wallpaper
if [ ! -d $folder ]; then
  mkdir -p $folder
fi
filename=`echo $url|grep -oE "[^/]*\.(jpg|jpeg|png)"`
if [ ! -f "$folder/$filename" ]; then
  echo "saving $filename to $folder/"
  wget -q -P $folder $url
fi
gsettings set org.gnome.desktop.background picture-uri file://$folder/$filename
gsettings set org.gnome.desktop.background picture-options 'centered'

